version: "3"

services:

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    networks:
      - mynetwork

  datastore:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - mynetwork
  
  tweet_collection:
    image: pedropod/tweet_collection:latest
    depends_on:
      - rabbitmq
      - datastore
    networks:
      - mynetwork
    command: ["./wait-for-it.sh", "-t", "0", "rabbitmq:5672", "--", "go", "run", "collect_publish.go"]

  reddit_news:
    image: pedropod/reddit_news:latest
    depends_on:
      - rabbitmq
      - datastore
    environment:
      - PYTHONUNBUFFERED=0
    networks:
      - mynetwork
    command: ["./wait-for-it.sh", "-t", "0", "rabbitmq:5672", "--" ,"python", "reddit_news.py"]
    

  sentiment_analysis:
    image: pedropod/sentiment_analysis:latest
    depends_on:
      - rabbitmq
      - datastore
      - tweet_collection
      - reddit_news
    environment:
      - PYTHONUNBUFFERED=0
    networks:
      - mynetwork
    command: ["./wait-for-it.sh", "-t", "0", "rabbitmq:5672", "--" ,"python", "sentiment.py"]

  frontend:
    image: pedropod/frontend:latest
    depends_on:
      - datastore
      - sentiment_analysis
    ports:
      - 3000:3000
    networks:
      - mynetwork
    command: ["./wait-for-it.sh", "-t", "0", "rabbitmq:5672", "--" ,"python", "front_end.py"]

networks: 
  mynetwork: